### ISSUE TITLE
textualog v0.1.2 - ImportError: Package 'textual.widgets' has no class 'ScrollView'

### ISSUE THREAD

**Issue by trevorhook** [rhuygen/textualog#2]
error presented trying to run textualog v0.1.2 from a fresh install. There were no errors shown during installation.

```
(textualog) C:\Users\trevor.hook\Scripts>textualog --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\trevor.hook\Scripts\textualog\Scripts\textualog.exe\__main__.py", line 4, in <module>
  File "C:\Users\trevor.hook\Scripts\textualog\Lib\site-packages\textualog\__main__.py", line 12, in <module>
    from textual.widgets import ScrollView
  File "C:\Users\trevor.hook\Scripts\textualog\Lib\site-packages\textual\widgets\__init__.py", line 62, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'ScrollView'
```

**Comment by trevorhook** [comment]
```
pip freeze
commonmark==0.9.1
importlib-metadata==4.13.0
nanoid==2.0.0
Pygments==2.13.0
rich==12.6.0
textual==0.7.0
textualog==0.1.2
zipp==3.11.0
```

**Comment by mjordan** [comment]
Can confirm:

```
textualog --version
Traceback (most recent call last):
  File "/home/mark/.local/bin/textualog", line 5, in <module>
    from textualog.__main__ import main
  File "/home/mark/.local/lib/python3.10/site-packages/textualog/__main__.py", line 12, in <module>
    from textual.widgets import ScrollView
  File "/home/mark/.local/lib/python3.10/site-packages/textual/widgets/__init__.py", line 64, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'ScrollView'
```

**Comment by sbcdave** [comment]
Same problem here trying to use TheengsExplorer which has a textual dependency. Anyone figure out how to deal with this yet?
